// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location_reporting_service.proto

package location_reporting_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Bearing              float64  `protobuf:"fixed64,3,opt,name=bearing,proto3" json:"bearing,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a1c9cf30bf023b3, []int{0}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetBearing() float64 {
	if m != nil {
		return m.Bearing
	}
	return 0
}

func (m *Location) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PushLocationsRequest struct {
	Locations            []*Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushLocationsRequest) Reset()         { *m = PushLocationsRequest{} }
func (m *PushLocationsRequest) String() string { return proto.CompactTextString(m) }
func (*PushLocationsRequest) ProtoMessage()    {}
func (*PushLocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a1c9cf30bf023b3, []int{1}
}

func (m *PushLocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushLocationsRequest.Unmarshal(m, b)
}
func (m *PushLocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushLocationsRequest.Marshal(b, m, deterministic)
}
func (m *PushLocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushLocationsRequest.Merge(m, src)
}
func (m *PushLocationsRequest) XXX_Size() int {
	return xxx_messageInfo_PushLocationsRequest.Size(m)
}
func (m *PushLocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushLocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushLocationsRequest proto.InternalMessageInfo

func (m *PushLocationsRequest) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

type PushLocationsResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushLocationsResponse) Reset()         { *m = PushLocationsResponse{} }
func (m *PushLocationsResponse) String() string { return proto.CompactTextString(m) }
func (*PushLocationsResponse) ProtoMessage()    {}
func (*PushLocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a1c9cf30bf023b3, []int{2}
}

func (m *PushLocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushLocationsResponse.Unmarshal(m, b)
}
func (m *PushLocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushLocationsResponse.Marshal(b, m, deterministic)
}
func (m *PushLocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushLocationsResponse.Merge(m, src)
}
func (m *PushLocationsResponse) XXX_Size() int {
	return xxx_messageInfo_PushLocationsResponse.Size(m)
}
func (m *PushLocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushLocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushLocationsResponse proto.InternalMessageInfo

func (m *PushLocationsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Location)(nil), "location_reporting_service.Location")
	proto.RegisterType((*PushLocationsRequest)(nil), "location_reporting_service.PushLocationsRequest")
	proto.RegisterType((*PushLocationsResponse)(nil), "location_reporting_service.PushLocationsResponse")
}

func init() { proto.RegisterFile("location_reporting_service.proto", fileDescriptor_2a1c9cf30bf023b3) }

var fileDescriptor_2a1c9cf30bf023b3 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x36, 0x56, 0xb4, 0x8e, 0x78, 0x09, 0x0a, 0xa1, 0x78, 0x28, 0xc5, 0x43, 0x4f, 0x8b, 0xbb,
	0xbe, 0x81, 0x67, 0x0f, 0x12, 0x6f, 0x5e, 0x96, 0x6e, 0x1d, 0x6a, 0xa0, 0x9b, 0xd4, 0xcc, 0x64,
	0x4f, 0x3e, 0x85, 0x4f, 0x2c, 0x9b, 0x6e, 0xb6, 0x28, 0xba, 0xe0, 0x71, 0xbe, 0x2f, 0xdf, 0x1f,
	0x81, 0xb2, 0x77, 0x6d, 0xc3, 0xc6, 0xd9, 0xa5, 0xc7, 0xc1, 0x79, 0x36, 0xb6, 0x5b, 0x12, 0xfa,
	0x8d, 0x69, 0x71, 0x36, 0x78, 0xc7, 0x4e, 0x16, 0x7f, 0xbf, 0xa8, 0x3e, 0x20, 0x7f, 0xdc, 0xb1,
	0xb2, 0x80, 0xbc, 0x6f, 0xd8, 0x70, 0x78, 0x45, 0x25, 0x4a, 0x51, 0x0b, 0xbd, 0xbf, 0xe5, 0x0d,
	0x9c, 0xf7, 0xce, 0x76, 0x23, 0x79, 0x1c, 0xc9, 0x09, 0x90, 0x0a, 0xce, 0x56, 0xd8, 0x78, 0x63,
	0x3b, 0x95, 0x45, 0x2e, 0x9d, 0x5b, 0x1d, 0x9b, 0x35, 0x12, 0x37, 0xeb, 0x41, 0x9d, 0x94, 0xa2,
	0xce, 0xf4, 0x04, 0x54, 0x2f, 0x70, 0xf5, 0x14, 0xe8, 0x2d, 0x35, 0x20, 0x8d, 0xef, 0x01, 0x89,
	0xe5, 0xc3, 0x36, 0x6d, 0x87, 0x29, 0x51, 0x66, 0xf5, 0xc5, 0xe2, 0x76, 0x76, 0x60, 0x67, 0x32,
	0xd0, 0x93, 0xac, 0x9a, 0xc3, 0xf5, 0x0f, 0x6f, 0x1a, 0x9c, 0xa5, 0x58, 0x96, 0x42, 0xdb, 0x22,
	0x51, 0x5c, 0x99, 0xeb, 0x74, 0x2e, 0x3e, 0x05, 0xa8, 0xbd, 0x55, 0x0a, 0x79, 0x1e, 0x33, 0xe4,
	0x06, 0x2e, 0xbf, 0xf9, 0xc9, 0xbb, 0x43, 0x8d, 0x7e, 0x9b, 0x55, 0xcc, 0xff, 0xa1, 0x18, 0xcb,
	0x56, 0x47, 0xab, 0xd3, 0xf8, 0x89, 0xf7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xfd, 0xc4,
	0xd7, 0xe8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocationReportingServiceClient is the client API for LocationReportingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationReportingServiceClient interface {
	PushLocations(ctx context.Context, in *PushLocationsRequest, opts ...grpc.CallOption) (*PushLocationsResponse, error)
}

type locationReportingServiceClient struct {
	cc *grpc.ClientConn
}

func NewLocationReportingServiceClient(cc *grpc.ClientConn) LocationReportingServiceClient {
	return &locationReportingServiceClient{cc}
}

func (c *locationReportingServiceClient) PushLocations(ctx context.Context, in *PushLocationsRequest, opts ...grpc.CallOption) (*PushLocationsResponse, error) {
	out := new(PushLocationsResponse)
	err := c.cc.Invoke(ctx, "/location_reporting_service.LocationReportingService/PushLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationReportingServiceServer is the server API for LocationReportingService service.
type LocationReportingServiceServer interface {
	PushLocations(context.Context, *PushLocationsRequest) (*PushLocationsResponse, error)
}

func RegisterLocationReportingServiceServer(s *grpc.Server, srv LocationReportingServiceServer) {
	s.RegisterService(&_LocationReportingService_serviceDesc, srv)
}

func _LocationReportingService_PushLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationReportingServiceServer).PushLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location_reporting_service.LocationReportingService/PushLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationReportingServiceServer).PushLocations(ctx, req.(*PushLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LocationReportingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "location_reporting_service.LocationReportingService",
	HandlerType: (*LocationReportingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushLocations",
			Handler:    _LocationReportingService_PushLocations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location_reporting_service.proto",
}
